### ISSUE TITLE
Image data is all zero

### ISSUE THREAD

**Issue by YuyingJin0111** [dusty-nv/jetbot_ros#2]
I successfully compiled all the packages,start the jetbot_camera node.But I get the image is all zero.
![TIM截图20190513203733](https://user-images.githubusercontent.com/46037829/57622189-a93c1080-75bf-11e9-9973-a130665e913e.png)

![TIM截图20190513204554](https://user-images.githubusercontent.com/46037829/57622412-1d76b400-75c0-11e9-9690-8caa66d6e5c7.png)

At the same time I can successfully run a separate jetson-interface.

thanks!

**Comment by localryu** [comment]
Hi. @YuyingJin0111 

I have a same error when I run the jetbot_camera node.

Did you solve the issue?
How can i solve this error...?

**Comment by alex-makarov** [comment]
Another possible workaround is to pass the converted RGBA via CPU memory. In jetbot_camera.cpp:

```
       // convert from YUV to RGBA
-       if( !camera->ConvertRGBA(imgCUDA, &imgRGBA) )
+       if( !camera->ConvertRGBA(imgCUDA, &imgRGBA, true) )
        {
                ROS_ERROR("failed to convert from NV12 to RGBA");
                return false;
        }

        // assure correct image size
        if( !camera_cvt->Resize(camera->GetWidth(), camera->GetHeight()) )
        {
                ROS_ERROR("failed to resize camera image converter");
                return false;
        }
+       memcpy(camera_cvt->ImageGPU(), imgRGBA, camera_cvt->GetSize()); 
 
        // populate the message
        sensor_msgs::Image msg;
```

**Comment by shannon112** [comment]
hi, @alex-makarov  I have tried your solution, it works. Thanks a lot. But image would flash when environment is changing. Do you know why?

**Comment by alex-makarov** [comment]
Not yet, I will look into it.

**Comment by alex-makarov** [comment]
@shannon112  - actually I'd recommend to use the patch from @nicolas-beaufort, works better for me.
