### ISSUE TITLE
How to install gazebo in nano properly? ./install_jetbot_model.sh shows error...

### ISSUE THREAD

**Issue by AK51** [dusty-nv/jetbot_ros#43]
Hi,

I have installed the gazebo by following this link
http://gazebosim.org/tutorials?tut=install_ubuntu
I can run gazebo. and I have closed the gazebo properly and restarted the nano just to be safe.
But when I run this line, there is an error.
./install_jetbot_model.sh

checking for: /home/jetbot/.gazebo
checking for: /home/jetbot/.gazebo/models
error: please install and run Gazebo once before running this script

Do I need to modify the install_jetbot_model.sh?
But in the file system
~/workspace/catkin_ws/src/jetbot_ros/gazebo/jetbot
Inside, there are 
meshes (folder) model.config model.sdf
there is no .gazebo

Btw, I am using this jetbot, it has its own SD card image. And I can run the motors and OLED. It won't affect the ros, right?
https://www.waveshare.net/wiki/JetBot_AI_Kit

Thanks.

**Comment by dusty-nv** [comment]
Can you check if you have /home/jetbot/.gazebo/models on your system?  If not, can you create it and run the script again please?
________________________________
From: AK51 ***@***.***>
Sent: Friday, July 23, 2021 12:57:21 AM
To: dusty-nv/jetbot_ros ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetbot_ros] How to install gazebo in nano properly? ./install_jetbot_model.sh shows error... (#43)


Hi,

I have installed the gazebo by following this link
http://gazebosim.org/tutorials?tut=install_ubuntu<https://nam11.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgazebosim.org%2Ftutorials%3Ftut%3Dinstall_ubuntu&data=04%7C01%7Cdustinf%40nvidia.com%7C9b147866fe7b4cb8124308d94d965ae2%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637626130441669647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5MoqTlWbHDGLFlKszzGa6ajk2MexH0YkOblMfgQYCs0%3D&reserved=0>
I can run gazebo. and I have closed the gazebo properly and restarted the nano just to be safe.
But when I run this line, there is an error.
./install_jetbot_model.sh

checking for: /home/jetbot/.gazebo
checking for: /home/jetbot/.gazebo/models
error: please install and run Gazebo once before running this script

Do I need to modify the install_jetbot_model.sh?
But in the file system
~/workspace/catkin_ws/src/jetbot_ros/gazebo/jetbot
Inside, there are
meshes (folder) model.config model.sdf
there is no .gazebo

Btw, I am using this jetbot, it has its own SD card image. And I can run the motors and OLED. It won't affect the ros, right?
https://www.waveshare.net/wiki/JetBot_AI_Kit<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.waveshare.net%2Fwiki%2FJetBot_AI_Kit&data=04%7C01%7Cdustinf%40nvidia.com%7C9b147866fe7b4cb8124308d94d965ae2%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637626130441669647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PrBk4Or1OSAz8VKsl%2FBcovOt0PshuQ9wgbNaaNQVHsM%3D&reserved=0>

Thanks.

**Comment by AK51** [comment]
![154416862](https://user-images.githubusercontent.com/8468724/127267698-34833091-9e3b-49fb-a51f-c51febd344c4.jpg)
![817253462](https://user-images.githubusercontent.com/8468724/127267702-70cc3637-6216-4b2a-ac7e-5ceec7987b20.jpg)
Dear Dusty,
the camera, oled and motor all works. I can open the gazebo too. I have created an empty models folder but the install_jetbot_model.sh still gives the same error...
I assume I didn't properly install the gazeboo...?
My pwd is under workspace/catkin_ws/src/jetson_ros which is different from yours. Will the https://www.waveshare.net/wiki/JetBot_AI_Kit has different path that causes the error?

Thanks

**Comment by AK51** [comment]
Hi, I re-do the whole thing with a new nano 4.6 SD image (not the jetbot image) Please let me know if I used a wrong image.
The nano4.6 image does not have jetbot folder, so I install it from wareshare(https://www.waveshare.net/wiki/JetBot_AI_Kit_%E6%95%99%E7%A8%8B%E4%BA%8C%E3%80%81%E5%AE%89%E8%A3%85%E9%95%9C%E5%83%8F) Sorry, it is not an English website.

git clone https://github.com/waveshare/jetbot
cd jetbot
sudo python3 setup.py install

And yes, after openning the Gazebo and add the jetbot model, I can see the model. Thx
