### ISSUE TITLE
ROS2-foxy Sparkfun jetbot - Container setup

### ISSUE THREAD

**Issue by ErnestoLozano** [dusty-nv/jetbot_ros#51]
Hi, I am trying to setup the docker container to use ros2 Foxy in my Sparkfun jetbot. I saw the latest commit, where the compatibility with the Sparkfun robot was finally added, thanks a lot for that. I pulled from git and executed the run.sh to get the container up and running. 
The problem is, once inside the container, none of the corresponding Sparkfun files are found, looking like the container is not in its latest version.
I tried running pull.sh but it did not introduce the desired updates. I then decided to build the container (build.sh) to see if that way I could have the latest version. However, doing so, I got stuck because of pip3 protobuf installation issues, which require Python >= 3.7. I am attaching the related lines of code in the DockerFile.

"RUN git clone https://github.com/dusty-nv/py3gazebo /opt/py3gazebo && \
    pip3 install protobuf>=2.6 --verbose && \
    pip3 install trollius --verbose && \
    pip3 install pynput --verbose "

Am I in the right track to get the latest container? If so, how could I successfully build the container?
Thanks a lot for your help in advance!

**Comment by dusty-nv** [comment]
Hi @ErnestoLozano, I recall that py3gazebo is an unused/unnecessary part of that container, so can comment out (or remove) those lines from the Dockerfile (lines 61-66).  And then try running `docker/build.sh` again.

**Comment by ErnestoLozano** [comment]
That fixed my problem! The building process takes quite some time, but it works.
Thanks for the answer and for giving support to the Sparkfun jetbot version!
