### ISSUE TITLE
rosrun jetbot_ros jetbot_motors.py

### ISSUE THREAD

**Issue by zouzhe1** [dusty-nv/jetbot_ros#9]
when i do     rosrun jetbot_ros jetbot_motors.py
it is error
------------------------------------------------------------------------------------------
File "/home/lb/workspace/catkin_ws/src/jetbot_ros/scripts/jetbot_motors.py", line 5, in <module>
    from Adafruit_MotorHAT import Adafruit_MotorHAT
ImportError: No module named Adafruit_MotorHAT
-----------------------------------------------------------------------------------------
but i had  run : 
pip install Adafruit-MotorHAT
pip3 install Adafruit-MotorHAT

where problem?

**Comment by raghakkrishnan** [comment]
I am also having the same issue

**Comment by egamor18** [comment]
I am also having the same issue. Has anyone been successful with it?
